version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: vulnerable-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vulnerable_app
    ports:
      - "3306:3306"
    volumes:
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js Backend
  backend:
    build: ./backend
    container_name: vulnerable-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: vulnerable_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/usr/src/app/uploads

  # React Frontend
  frontend:
    build: ./frontend
    container_name: vulnerable-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
